name: Echo on fork

on:
  pull_request:
    branches:
      - main

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - name: echo on fork project
        run: echo "This project is forked"

